# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcTmuxMenu < Formula
  desc "Interactive tmux session manager with AI-powered previews for Claude Code"
  homepage "https://github.com/mousems/cc-tmux-menu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_darwin_amd64.tar.gz"
      sha256 "f399dbf6fa61b403d29818682135402dcff498ee6471802b0568c3be78689c52"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_darwin_arm64.tar.gz"
      sha256 "61625644bb3e10381ed278059144f6adc091bdfba5ce3e44825f9413ea63f442"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_linux_amd64.tar.gz"
      sha256 "5f6bf131a9f32ae73ae3797a3aa00707f33d402a8381878bd83e435f2a9a4973"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_linux_arm64.tar.gz"
      sha256 "977b4a9ea4761b129f2a8cc0b21123d59056ed1c439f2ea27e33ab4d22f86e65"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/cc-tmux-menu --version")
  end
end
