# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcTmuxMenu < Formula
  desc "Interactive tmux session manager with AI-powered previews for Claude Code"
  homepage "https://github.com/mousems/cc-tmux-menu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_darwin_amd64.tar.gz"
      sha256 "ef2476e1383a45a156f33dc30d8fa949809fb587825074d4758c72a1c15d7536"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_darwin_arm64.tar.gz"
      sha256 "81f8e7de34604819f1b57f56860c1ed3c9e5b7681905d028be112b1494cb476a"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_linux_amd64.tar.gz"
      sha256 "f9bb97338d5ef85227ad4dedf018e368c70ae83ce9df525f8c4aae489cf61439"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.1.0/cc-tmux-menu_linux_arm64.tar.gz"
      sha256 "d091f6115fbbd8a8ff4ebe967b33781cb30312c4e87613be244c30993fba5407"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/cc-tmux-menu --version")
  end
end
