# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcTmuxMenu < Formula
  desc "Interactive tmux session manager with AI-powered previews for Claude Code"
  homepage "https://github.com/mousems/cc-tmux-menu"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.2.0/cc-tmux-menu_darwin_amd64.tar.gz"
      sha256 "8b4f513fb334517ba9bb0cb235d4efa5c3e0bc21f7030b5fd45b1e04b3a572f0"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.2.0/cc-tmux-menu_darwin_arm64.tar.gz"
      sha256 "0e2ba0111eb10a7addecf2a6ea52f1251d51c26d4a5ebea907343c37f8ee8d74"

      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.2.0/cc-tmux-menu_linux_amd64.tar.gz"
      sha256 "1c57ee6bf5f1ee00f9d0d7f3fab6ce5eb8259b55ffc3bfda591e3d207dbda9d1"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mousems/cc-tmux-menu/releases/download/v0.2.0/cc-tmux-menu_linux_arm64.tar.gz"
      sha256 "b37b654fdab80627a2f42e03da41a0b9054fb739a9dac86686fdfa3a105b512e"
      define_method(:install) do
        bin.install "cc-tmux-menu"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/cc-tmux-menu --version")
  end
end
